export const ActionTypes = {
    FETCH_PRODUCTS : 'FETCH_PRODUCTS',
    SET_PRODUCTS : 'SET_PRODUCTS',

    FETCH_PRODUCTS_DETAILS : 'FETCH_PRODUCTS_DETAILS',
    SET_PRODUCTS_DETAILS : 'SET_PRODUCTS_DETAILS',

    FETCH_PRODUCTS_CATEGORY : 'FETCH_PRODUCTS_CATEGORY',
    SET_PRODUCTS_CATEGORY : 'SET_PRODUCTS_CATEGORY',

    IS_FETCHING : 'IS_FETCHING',

    FETCH_CATEGORY_PRODUCT: 'FETCH_CATEGORY_PRODUCT',
    SET_CATEGORY_PRODUCT: 'SET_CATEGORY_PRODUCT',

    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    LOGOUT: 'LOGOUT',

    LIKED: 'LIKED',
};